version: '3.9'
services:
  invoicecache:
    network_mode: bridge
    container_name: 'ms-invoicecache-local-sandbox'
    image: 'evil.sundsvall.se/ms-invoicecache:latest'
    depends_on:
      - invoicecache-db
      - raindance-db
      - invoicecache-wiremock
    links:
      - invoicecache-db:invoice
      - raindance-db:raindance
      - invoicecache-wiremock:wiremock
    build:
      context: .
    ports:
      - '8080:8080'
    environment:
      - TZ=Europe/Stockholm
      - "JAVA_OPTS=$JAVA_OPTS -Xmx256m -Xms128m"
      #Spring profile
      - spring_profiles_active=sandbox

      #Party
      - integration_party_url=http://wiremock:8080/party
      - integration_party_oauth2-token-url=http://wiremock:8080/token
      - integration_party_oauth2_client_id=override
      - integration_party_oauth2_client_secret=override

      #Local-DB properties
      - spring_datasource_url=jdbc:mariadb://invoice/ms-invoicecache
      - spring_datasource_driver_class_name=org.mariadb.jdbc.Driver
      - spring_datasource_username=dbinvoicecache
      - spring_datasource_password=dbinvoicecache
      - spring_jpa_properties_hibernate.dialect=org.hibernate.dialect.MariaDB103Dialect
      - spring_jpa_hibernate_ddl-auto=update
      - spring_batch_jdbc_initialize_schema=always

      #Raindance properties
      - spring_raindance_datasource_url=jdbc:mariadb://raindance/raindance
      - spring_raindance_datasource_driver_class_name=org.mariadb.jdbc.Driver
      - spring_raindance_datasource_username=raindance
      - spring_raindance_datasource_password=raindance

  invoicecache-db:
    network_mode: bridge
    container_name: invoicecache-db
    image: mariadb:10.9.2
    ports:
      - "33061:3306"
    volumes:
        - ./init-local.sql:/docker-entrypoint-initdb.d/init-local.sql
    command: "--init-file /docker-entrypoint-initdb.d/init-local.sql"
    restart: "no"
    environment:
      TZ: 'Europe/Stockholm'
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: 'ms-invoicecache'
      MYSQL_USER: 'dbinvoicecache'
      MYSQL_PASSWORD: 'dbinvoicecache'

  raindance-db:
    network_mode: bridge
    container_name: raindance-db
    volumes:
      - ./init-raindance.sql:/docker-entrypoint-initdb.d/init-raindance.sql
    command: "--init-file /docker-entrypoint-initdb.d/init-raindance.sql"
    image: mariadb:10.9.2
    ports:
      - "33062:3306"
    restart: "no"
    environment:
      TZ: 'Europe/Stockholm'
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: 'raindance'
      MYSQL_USER: 'raindance'
      MYSQL_PASSWORD: 'raindance'

  invoicecache-wiremock:
    network_mode: bridge
    image: wiremock/wiremock:2.34.0
    restart: always
    expose:
      - '8080'
    volumes:
      - $PWD/src/test/resources/wiremock:/home/wiremock