-- Spring Batch 5.2 (Spring Boot 4) renamed BATCH_JOB_SEQ to BATCH_JOB_INSTANCE_SEQ
CREATE SEQUENCE IF NOT EXISTS BATCH_JOB_INSTANCE_SEQ START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775806 INCREMENT BY 1 NOCACHE NOCYCLE ENGINE =InnoDB;
DROP SEQUENCE IF EXISTS BATCH_JOB_SEQ;
