integration:
    party:
        oauth2-client-id: override
        oauth2-client-secret: override
        oauth2-token-url: http://localhost:${wiremock.server.port}/token
        url: http://localhost:${wiremock.server.port}/party
    smb:
        cron: 0 30 5 * * MON-FRI
        domain: domain.local
        password: password
        remoteDir: /
        shareAndDir: test
        user: user
invoice:
    scheduled:
        fixedrate: PT1H
        initialdelay: PT0S
raindance:
    invoice:
        outdated: PT1H
    sql:
        filename: local-query.esscueell
spring:
    cache:
        type: none
    flyway:
        enabled: true
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            jakarta:
                persistence:
                    schema-generation:
                        scripts:
                            create-target: target/database/generated-schema.sql
